listeners:
  - motd: 'Deepslate Proxy'
    priorities: []
    bind_local_address: true
    host: 127.0.0.1:25566
    max_players: 10
    force_default_server: false
    ping_passthrough: false
    proxy_protocol: false
    tab_list: GLOBAL_PING
    query_enabled: false
    custom_channel_extchunk: true   # ← REQUIRED for extended chunks

servers:
  default:
    # Replace with the server you actually want to join
    address: SKilLMcs4.aTERNos.Me:16224
    restricted: false

ip_forward: false
online_mode: true
